### ISSUE TITLE
alpha.12 - `origins:attribute` power bonuses are not persistent; they are lost on death and never reapply.

### ISSUE THREAD

**Issue by muon-rw** [apace100/origins-fabric#806]

**Comment by eggohito** [comment]
This is actually already been fixed in upstream. I'll close this issue once the new alpha build is out

**Comment by muon-rw** [comment]
Great to hear, thank you

**Comment by therealabc** [comment]
> This is actually already been fixed in upstream. I'll close this issue once the new alpha build is out

im playing on the latest version and the issue is still there

**Comment by Slab0fSlate** [comment]
before i finally close this tab, id like to leave the temporary workaround ive started using to combat this:

put all your attributes under one multi-power if you want to keep this simpler
then **revoke and re-grant that power on respawn**

this is the only example i have atm, tacked it onto a thing i have that just assures a variable doesnt get funky, but im giving you the whole sub-power cause im lazy:

```
"scale": {
        "type": "origins:action_on_callback",
        "entity_action_chosen": {
            "type": "origins:change_resource",
            "resource": "*:mini_lil",
            "change": 0,
            "operation": "set"
        },
        "execute_chosen_when_orb": true,
        "entity_action_lost": {
            "type": "origins:execute_command",
            "command": "scale reset @s"
        },
        "entity_action_respawned": {
            "type": "origins:and",
            "actions": [
                    {
                        "type": "origins:change_resource",
                        "resource": "*:mini_lil",
                        "change": 0,
                        "operation": "set"
                    },
                    {    
                        "type": "origins:revoke_power",
                        "power": "flea:health",
                        "source": "flea:flea"
                    },
                    {
                            "type": "origins:grant_power",
                            "power": "flea:health",
                            "source": "flea:flea"
                    }
                
            ]
        }
    }
```

**Comment by zonkerjackson** [comment]
can you update the existing pack for 1.21.1 with the fixes for each? I tried inputing them with all the code you provided, renaming to each and everything, I couldnt get it to work

**Comment by Slab0fSlate** [comment]
theres some slightly goofy things you can do for editing the base origins, though i dont have those edits done rn. but im updating a set of origins for a server, so ill eventually have to fix the base ones as well...

ill be sure to send the needed files when ive done them 👍

**Comment by zonkerjackson** [comment]
I'm looking forward to it! Thank you

**Comment by Slab0fSlate** [comment]
[here we are! - Alpha12 base origins fix](https://github.com/Slab0fSlate/Origins-Alpha-12-fix)  

a little messy, but working  
should hopefully have no issues, but, we'll see  

sorry for the slight wait 🫡

**Comment by zonkerjackson** [comment]
Thank you! I will try and get this fix working, but will a version of this fix be downloadable on modrinth for those who are less confident with code? 1.21.1 fabric specifically?

Update I added it into my modpack, it shows up as a data pack, however the same error is still occurring to the merling, though I may be doing it wrong

**Comment by Slab0fSlate** [comment]
im Brand new to actually uploading my code, lol  
  uuhh.....    i   thhink i can turn this into a fabric mod  
ok so:  
yeah this is a datapack, 1.21.1 specifically, intended to be put into your datapacks folder like you would with any normal origins datapack

something i forgot to account for and might be your issue(?):  
hitting the "code", "download zip" buttons downloads the readme and licence as well, messing up the datapack format  

## two options if thats the case:
1. in github, if you instead click on "fix 2.0.0.zip" and then "view raw" itll download the datapack as intended

2. you can unzip the downloaded file, and should just be able to take out the "fix 2.0.0.zip"

---

you familiar with how to put in datapacks at all?

**Comment by zonkerjackson** [comment]
Not with origins data packs, the only way I've installed things is with mod managers, I'm trying out the view raw fix now

**Comment by Slab0fSlate** [comment]
origins datapacks are very similar to the client side ones youre likely used to, though just install a little different

for single player worlds:
through your mod loader (curseforge, modrinth, etc), view your modpack, click the ... button, "Open Folder".  
ignore the "datapacks" folder you see in there, you actually want to open "saves", the world you want to add it to, and Now you wanna open the one that says "Datapacks"  
just drop the zip file in there and re-open your world

for servers:
it differs a lot depending on your provider, but figure out where your datapacks folder is, tends to be the first one you spot  
just drop the zip file into that folder and restart the server

**Comment by zonkerjackson** [comment]
Im using bisect hosting, I found a folder called data which has a name of another datapack installed so im just guessing its correct lol, datapacks isnt a folder on its own so I think its right, I just dropped in the zip and the server is restarting

**Comment by Slab0fSlate** [comment]
nice, i havent been in the guts of bisect before, so i wouldnt know if thats right or not

i also wanna add: you might have to reselect your origin (/origin gui [username]) if it doesnt do that automatically, cause this pack replaces the actual base origins with the ones that work

**Comment by zonkerjackson** [comment]
I selected my origin again which in this case was shulk, worked fine, died, lost the extra armor perk,

I found a folder called data packs im trying again

**Comment by zonkerjackson** [comment]
Its fixed! thank you so much! Ill be sure to let you know if any other bugs show themselves

**Comment by Slab0fSlate** [comment]
fantastic! have fun! and yeah lemme know if anything isnt right at all, even if its just a typo or somn, lol, it'd be so appreciated

**Comment by eggohito** [comment]
This should now be fixed in Origins 1.13.0-pre.1 👍
